/*
    (c) 2018 Microchip Technology Inc. and its subsidiaries. 
    
    Subject to your compliance with these terms, you may use Microchip software and any 
    derivatives exclusively with Microchip products. It is your responsibility to comply with third party 
    license terms applicable to your use of third party software (including open source software) that 
    may accompany Microchip software.
    
    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
    IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS 
    FOR A PARTICULAR PURPOSE.
    
    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP 
    HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO 
    THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL 
    CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT 
    OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS 
    SOFTWARE.
*/

#include "../include/evsys.h"

/**
 * \brief Initialize evsys interface
 */
int8_t EVSYS_Initialize()
{
    //ASYNCCH0 PORTA_PIN6; 
	EVSYS.ASYNCCH0 = 0x10;

    //ASYNCCH1 OFF; 
	EVSYS.ASYNCCH1 = 0x00;

    //ASYNCCH2 OFF; 
	EVSYS.ASYNCCH2 = 0x00;

    //ASYNCCH3 OFF; 
	EVSYS.ASYNCCH3 = 0x00;

    //ASYNCUSER0 ASYNCCH0; 
	EVSYS.ASYNCUSER0 = 0x03;

    //ASYNCUSER1 OFF; 
	EVSYS.ASYNCUSER1 = 0x00;

    //ASYNCUSER2 OFF; 
	EVSYS.ASYNCUSER2 = 0x00;

    //ASYNCUSER3 OFF; 
	EVSYS.ASYNCUSER3 = 0x00;

    //ASYNCUSER4 OFF; 
	EVSYS.ASYNCUSER4 = 0x00;

    //ASYNCUSER5 OFF; 
	EVSYS.ASYNCUSER5 = 0x00;

    //ASYNCUSER6 OFF; 
	EVSYS.ASYNCUSER6 = 0x00;

    //ASYNCUSER7 OFF; 
	EVSYS.ASYNCUSER7 = 0x00;

    //ASYNCUSER8 OFF; 
	EVSYS.ASYNCUSER8 = 0x00;

    //ASYNCUSER9 OFF; 
	EVSYS.ASYNCUSER9 = 0x00;

    //ASYNCUSER10 OFF; 
	EVSYS.ASYNCUSER10 = 0x00;

    //SYNCCH0 OFF; 
	EVSYS.SYNCCH0 = 0x00;

    //SYNCCH1 OFF; 
	EVSYS.SYNCCH1 = 0x00;

    //SYNCUSER0 OFF; 
	EVSYS.SYNCUSER0 = 0x00;

    //SYNCUSER1 OFF; 
	EVSYS.SYNCUSER1 = 0x00;

	return 0;
}